config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :vehicle_types do
      collection do
        post :import
      end
    end

    resources :brands do
      collection do
        post :import
      end
    end

    resources :fuels do
      collection do
        post :import
      end
    end

    devise_for :users
    root to: 'welcome#home'
  end
end

app/views/shared/_flash_messages.html.slim
- flash.each do |type, message|
  div[class="alert alert-#{type=='notice' ? 'success' : 'danger'} alert-dismissable fade in"]
    button[class='close' data-dismiss='alert' aria-label='Close']
      span[aria-hidden='true'] &times;
    = message

app/views/shared/_import_form.html.slim
section.import_form
  - if policy(resource_class).import?
    h2= t 'import_form.title', resources: resources_human

    section.instructions
    = form_tag import_resources_path, multipart: true, class: :highlight do
      fieldset
        p= t 'import_form.instructions'
        ul
          - resource_class.io_attributes.each do |attr|
            li= attr
        p= t 'import_form.existing_key_behaviour_html', column: resource_class.io_attributes.first, resource: resource_human
        p= t 'import_form.select_and_import'
        = file_field_tag :file
      section.actions
        = submit_tag t('import_form.import'), class: :primary

app/views/shared/_navbar.html.slim
.container-fluid
  .navbar-header
    button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to 'neoDAV', root_path, class: 'navbar-brand'
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    ul.nav.navbar-nav
      li.dropdown
        a.dropdown-toggle href='#' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'
          = t '.maintenance'
          span.caret
        ul.dropdown-menu
          li= link_to Fuel.model_name.human(count: 2),        fuels_path         if policy(Fuel).index?
          li= link_to Brand.model_name.human(count: 2),       brands_path        if policy(Brand).index?
          li= link_to VehicleType.model_name.human(count: 2), vehicle_types_path if policy(VehicleType).index?
    ul.nav.navbar-nav.navbar-right
      - if I18n.locale == :pt
        li= link_to 'EN', locale: :en
      - else
        li= link_to 'PT', locale: :pt
      - if user_signed_in?
        li= link_to current_user.email, edit_user_registration_path(current_user)
        li= link_to t('.logout'), destroy_user_session_path, method: :delete
      - else
        li= link_to t('.signup'), new_user_registration_path
        li= link_to t('.login'), new_user_session_path

app/views/shared/_search_form.html.slim
section.search_form
  = form_tag resources_path, method: :get do
    div.search_field_button
      = text_field_tag  :query, query, autofocus: true,
                        placeholder: t('.placeholder', resource: resources_human.downcase)
      span
        = submit_tag t('.go'), name: nil
  section.search_actions
    - if policy(resource_class).new?
      span= t '.or'
      = link_to t('.add_new'), new_resource_path, class: :primary

app/views/shared/_search_results.html.slim
section.search_results
  - if resources.empty?
    p= t '.results', resource: resource_human.downcase
  - else
    p
      span= t '.export'
      = link_to 'CSV', resources_path(params.merge(format: :csv))
    == render resources
    = paginate resources

app/views/shared/new_or_edit.html.slim
header.content_title
  h1= t "actions.#{action_name.downcase}_resource", resource: resource_human

== render 'form'