config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :vehicle_types do
      collection do
        post :import
      end
    end

    resources :brands do
      collection do
        post :import
      end
    end

    resources :fuels do
      collection do
        post :import
      end
    end

    devise_for :users
    root to: 'welcome#home'
  end
end

app/controllers/vehicle_types_controller.rb
class VehicleTypesController < ApplicationController
  before_action :set_vehicle_type, only: [:show, :edit, :update, :destroy]

  def index
    @query = params[:query]
    @vehicle_types = VehicleType.search @query
    @paged_vehicle_types = @vehicle_types.page params[:page]
    authorize @paged_vehicle_types
    respond_to do |format|
      format.html
      format.json
      format.csv  { send_data @vehicle_types.to_csv, filename: export_filename }
    end
  end

  def show
  end

  def new
    @vehicle_type = VehicleType.new
    authorize @vehicle_type
    render 'shared/new_or_edit'
  end

  def edit
    render 'shared/new_or_edit'
  end

  def create
    @vehicle_type = VehicleType.new vehicle_type_params
    authorize @vehicle_type
    respond_to do |format|
      if @vehicle_type.save
        format.html { redirect_to vehicle_types_url, notice: t('notice.create.success', resource: VehicleType.model_name.human) }
        format.json { render :show, status: :created, location: @vehicle_type }
      else
        format.html { render 'shared/new_or_edit' }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @vehicle_type.update(vehicle_type_params)
        format.html { redirect_to vehicle_types_url, notice: t('notice.update.success', resource: VehicleType.model_name.human) }
        format.json { render :show, status: :ok, location: @vehicle_type }
      else
        format.html { render 'shared/new_or_edit' }
        format.json { render json: @vehicle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vehicle_type.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_types_url, notice: t('notice.destroy.success', resource: VehicleType.model_name.human) }
      format.json { head :no_content }
    end
  end

  def import
    authorize VehicleType
    if params[:file]
      VehicleType.from_csv params[:file]
      redirect_to vehicle_types_url, notice: t('notice.import.success', resource: VehicleType.model_name.human(count: 2))
    else
      redirect_to vehicle_types_url, alert: t('alert.import.failure', resource: VehicleType.model_name.human(count: 2))
    end
  end

  def autocomplete
    vehicle_types = VehicleType.where("description ilike '#{params[:term]}%'").order(:description)
    authorize vehicle_types
    render json: vehicle_types.pluck(:description)
  end

  private
    def set_vehicle_type
      @vehicle_type = VehicleType.friendly.find params[:id]
      authorize @vehicle_type
    end

    def vehicle_type_params
      params.require(:vehicle_type).permit(:code, :description)
    end
end

app/views/vehicle_types/_form.html.slim
section.content
  = simple_form_for @vehicle_type, html: { class: :highlight } do |f|
      = f.error_notification
      = f.error :base

      fieldset
        section.primary_details
          = f.input :code, autofocus: true
          = f.input :description

      section.actions
        = f.button :submit, data: { disable_with: t('simple_form.submitting') }, class: :primary
        = link_to t('actions.back_to_resources_list', resources: resources_human), vehicle_types_path, class: :default

app/views/vehicle_types/_vehicle_type.html.slim
- present vehicle_type do |v|
  section.summary
    header.reference
      h3= v.description
    section.summary-details
      p= v.details
    section.summary-actions
      = v.edit_link
      = v.destroy_link

app/views/vehicle_types/index.html.slim
header.content_title
  h1= resources_human

section.content
  == render partial: 'shared/search_form',    locals: { query: @query }
  == render partial: 'shared/search_results', locals: { resources: @paged_vehicle_types }
  == render partial: 'shared/import_form'

section.sidebar

app/views/vehicle_types/show.html.slim
header.content_title
  h1= @vehicle_type.description

section.content
  section.details
    h3= @vehicle_type.code
  section.actions
    -if policy(@vehicle_type).edit?
      = link_to t('actions.edit'), edit_vehicle_type_path(@vehicle_type), class: :primary
    - if policy(@vehicle_type).destroy?
      = link_to t('actions.destroy'), @vehicle_type, method: :delete,
                                      data: { confirm: t('actions.are_you_sure') },
                                      class: :danger
    = link_to t('actions.back_to_resources_list', resources: resources_human), vehicle_types_path, class: :default