config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :vehicle_types do
      collection do
        post :import
      end
    end

    resources :brands do
      collection do
        post :import
      end
    end

    resources :fuels do
      collection do
        post :import
      end
    end

    devise_for :users
    root to: 'welcome#home'
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :code,        presence: true, uniqueness: true
  validates :description, presence: true, uniqueness: true

  default_scope { order :description }

  include Serializable
  io_attributes :code, :description

  extend FriendlyId
  friendly_id :code, use: :slugged

  def self.search query
    if query.present?
      where "code = '#{query}' OR description ilike '%#{query}%'"
    else
      all
    end
  end

  def to_s
    code
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  def index
    @query = params[:query]
    @brands = Brand.search @query
    @paged_brands = @brands.page params[:page]
    authorize @paged_brands
    respond_to do |format|
      format.html
      format.json
      format.csv  { send_data @brands.to_csv, filename: export_filename }
    end
  end

  def show
  end

  def new
    @brand = Brand.new
    authorize @brand
    render 'shared/new_or_edit'
  end

  def edit
    render 'shared/new_or_edit'
  end

  def create
    @brand = Brand.new brand_params
    authorize @brand
    respond_to do |format|
      if @brand.save
        format.html { redirect_to brands_url, notice: t('notice.create.success', resource: Brand.model_name.human) }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render 'shared/new_or_edit' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brands_url, notice: t('notice.update.success', resource: Brand.model_name.human) }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render 'shared/new_or_edit' }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: t('notice.destroy.success', resource: Brand.model_name.human) }
      format.json { head :no_content }
    end
  end

  def import
    authorize Brand
    if params[:file]
      Brand.from_csv params[:file]
      redirect_to brands_url, notice: t('notice.import.success', resource: Brand.model_name.human(count: 2))
    else
      redirect_to brands_url, alert: t('alert.import.failure', resource: Brand.model_name.human(count: 2))
    end
  end

  def autocomplete
    brands = Brand.where("description ilike '#{params[:term]}%'").order(:description)
    authorize brands
    render json: brands.pluck(:description)
  end

  private
    def set_brand
      @brand = Brand.friendly.find params[:id]
      authorize @brand
    end

    def brand_params
      params.require(:brand).permit(:code, :description)
    end
end

app/views/brands/_brand.html.slim
- present brand do |f|
  section.summary
    header.reference
      h3= f.description
    section.summary-details
      p= f.details
    section.summary-actions
      = f.edit_link
      = f.destroy_link

app/views/brands/_form.html.slim
section.content
  = simple_form_for @brand, html: { class: :highlight } do |f|
      = f.error_notification
      = f.error :base

      fieldset
        section.primary_details
          = f.input :code, autofocus: true
          = f.input :description

      section.actions
        = f.button :submit, data: { disable_with: t('simple_form.submitting') }, class: :primary
        = link_to t('actions.back_to_resources_list', resources: resources_human), brands_path, class: :default

app/views/brands/index.html.slim
header.content_title
  h1= resources_human

section.content
  == render partial: 'shared/search_form',    locals: { query: @query }
  == render partial: 'shared/search_results', locals: { resources: @paged_brands }
  == render partial: 'shared/import_form'

section.sidebar

app/views/brands/show.html.slim
header.content_title
  h1= @brand.description

section.content
  section.details
    h3= @brand.code
  section.actions
    -if policy(@brand).edit?
      = link_to t('actions.edit'), edit_brand_path(@brand), class: :primary
    - if policy(@brand).destroy?
      = link_to t('actions.destroy'), @brand, method: :delete,
                                      data: { confirm: t('actions.are_you_sure') },
                                      class: :danger
    = link_to t('actions.back_to_resources_list', resources: resources_human), brands_path, class: :default