config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :vehicle_types do
      collection do
        post :import
      end
    end

    resources :brands do
      collection do
        post :import
      end
    end

    resources :fuels do
      collection do
        post :import
      end
    end

    devise_for :users
    root to: 'welcome#home'
  end
end

app/models/fuel.rb
class Fuel < ActiveRecord::Base
  validates :code,        presence: true, uniqueness: true
  validates :description, presence: true, uniqueness: true

  default_scope { order :description }

  include Serializable
  io_attributes :code, :description

  extend FriendlyId
  friendly_id :code, use: :slugged

  def self.search query
    if query.present?
      where "code = '#{query}' OR description ilike '%#{query}%'"
    else
      all
    end
  end

  def to_s
    code
  end
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
  before_action :set_fuel, only: [:show, :edit, :update, :destroy]

  def index
    @query = params[:query]
    @fuels = Fuel.search @query
    @paged_fuels = @fuels.page params[:page]
    authorize @paged_fuels
    respond_to do |format|
      format.html
      format.json
      format.csv  { send_data @fuels.to_csv, filename: export_filename }
    end
  end

  def show
  end

  def new
    @fuel = Fuel.new
    authorize @fuel
    render 'shared/new_or_edit'
  end

  def edit
    render 'shared/new_or_edit'
  end

  def create
    @fuel = Fuel.new fuel_params
    authorize @fuel
    respond_to do |format|
      if @fuel.save
        format.html { redirect_to fuels_url, notice: t('notice.create.success', resource: Fuel.model_name.human) }
        format.json { render :show, status: :created, location: @fuel }
      else
        format.html { render 'shared/new_or_edit' }
        format.json { render json: @fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @fuel.update(fuel_params)
        format.html { redirect_to fuels_url, notice: t('notice.update.success', resource: Fuel.model_name.human) }
        format.json { render :show, status: :ok, location: @fuel }
      else
        format.html { render 'shared/new_or_edit' }
        format.json { render json: @fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fuel.destroy
    respond_to do |format|
      format.html { redirect_to fuels_url, notice: t('notice.destroy.success', resource: Fuel.model_name.human) }
      format.json { head :no_content }
    end
  end

  def import
    authorize Fuel
    if params[:file]
      Fuel.from_csv params[:file]
      redirect_to fuels_url, notice: t('notice.import.success', resource: Fuel.model_name.human(count: 2))
    else
      redirect_to fuels_url, alert: t('alert.import.failure', resource: Fuel.model_name.human(count: 2))
    end
  end

  def autocomplete
    fuels = Fuel.where("description ilike '#{params[:term]}%'").order(:description)
    authorize fuels
    render json: fuels.pluck(:description)
  end

  private
    def set_fuel
      @fuel = Fuel.friendly.find params[:id]
      authorize @fuel
    end

    def fuel_params
      params.require(:fuel).permit(:code, :description)
    end
end

app/views/fuels/_form.html.slim
section.content
  = simple_form_for @fuel, html: { class: :highlight } do |f|
      = f.error_notification
      = f.error :base

      fieldset
        section.primary_details
          = f.input :code, autofocus: true
          = f.input :description

      section.actions
        = f.button :submit, data: { disable_with: t('simple_form.submitting') }, class: :primary
        = link_to t('actions.back_to_resources_list', resources: resources_human), fuels_path, class: :default

app/views/fuels/_fuel.html.slim
- present fuel do |f|
  section.summary
    header.reference
      h3= f.description
    section.summary-details
      p= f.details
    section.summary-actions
      = f.edit_link
      = f.destroy_link

app/views/fuels/index.html.slim
header.content_title
  h1= resources_human

section.content
  == render partial: 'shared/search_form',    locals: { query: @query }
  == render partial: 'shared/search_results', locals: { resources: @paged_fuels }
  == render partial: 'shared/import_form'

section.sidebar

app/views/fuels/show.html.slim
header.content_title
  h1= @fuel.description

section.content
  section.details
    h3= @fuel.code
  section.actions
    -if policy(@fuel).edit?
      = link_to t('actions.edit'), edit_fuel_path(@fuel), class: :primary
    - if policy(@fuel).destroy?
      = link_to t('actions.destroy'), @fuel, method: :delete,
                                      data: { confirm: t('actions.are_you_sure') },
                                      class: :danger
    = link_to t('actions.back_to_resources_list', resources: resources_human), fuels_path, class: :default